parameters: {}
packages:
  - name: slack_observers
    environment:
      ASANA_TOKEN: "${ASANA_TOKEN}"
      ASANA_ORG: "${ASANA_ORG}"
      SLACK_BOT_TOKEN: "${SLACK_BOT_TOKEN}"
      SLACK_SEC_TOKEN: "${SLACK_SEC_TOKEN}"
      SLACK_SIGN: "${SLACK_SIGN}"
      BOT_CHANNEl_SLACK: "${BOT_CHANNEl_SLACK}"
      SLACK_TEAM_ID: "${SLACK_TEAM_ID}"
      SLACK_API_APP_ID: "${SLACK_API_APP_ID}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_HOST}"
      DB_USER: "${DB_HOST}"
      DB_PASS: "${DB_HOST}"
      DB_NAME: "${DB_HOST}"
      LOG_DESTINATIONS: ${LOG_DESTINATIONS}
    functions:
      - name: slack_asana
        runtime: python:default
      - name: base_observer
        runtime: python:default
